# Generated by Django 3.0.3 on 2020-05-13 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ['-created']},
        ),
        migrations.AddField(
            model_name='patient',
            name='first_password',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
