# Generated by Django 3.0 on 2020-02-18 14:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('departament', '0002_auto_20200218_1413'),
        ('profiles', '0002_auto_20191204_1150'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='department_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='doctors', to='departament.Departament'),
        ),
    ]
