# Generated by Django 3.0 on 2019-12-03 11:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MedicalCenter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
            ],
            options={
                'verbose_name': 'Medical Center',
                'verbose_name_plural': 'Medical Centers',
            },
        ),
        migrations.CreateModel(
            name='MedCenterPhoto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('image', models.ImageField(upload_to='')),
                ('medical_center', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='med_center.MedicalCenter')),
            ],
            options={
                'verbose_name': 'Med-Center Photo',
                'verbose_name_plural': 'Med-Center Photos',
            },
        ),
    ]
