# Generated by Django 3.0.3 on 2020-05-14 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('med_center', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicalcenter',
            name='doctor_default_image',
            field=models.ImageField(blank=True, null=True, upload_to='med-center-photos/'),
        ),
        migrations.AddField(
            model_name='medicalcenter',
            name='facebook_link',
            field=models.CharField(blank=True, max_length=800, null=True),
        ),
        migrations.AddField(
            model_name='medicalcenter',
            name='insta_link',
            field=models.CharField(blank=True, max_length=800, null=True),
        ),
        migrations.AddField(
            model_name='medicalcenter',
            name='patient_default_image',
            field=models.ImageField(blank=True, null=True, upload_to='med-center-photos/'),
        ),
        migrations.AddField(
            model_name='medicalcenter',
            name='youtube_link',
            field=models.CharField(blank=True, max_length=800, null=True),
        ),
    ]
