# Generated by Django 3.0 on 2019-12-03 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('med_center', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medcenterphoto',
            name='image',
            field=models.ImageField(upload_to='med-center-photos/'),
        ),
    ]
