# Generated by Django 3.0 on 2019-12-04 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('med_center', '0002_auto_20191203_1213'),
    ]

    operations = [
        migrations.AddField(
            model_name='medcenterphoto',
            name='is_logo',
            field=models.BooleanField(default=False),
        ),
    ]
