# Generated by Django 3.0.3 on 2020-05-26 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('med_center', '0002_auto_20200514_1815'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicalcenter',
            name='tagline',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
