# Generated by Django 3.0 on 2019-12-04 12:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('med_center', '0003_medcenterphoto_is_logo'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScheduleTime',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('med_center', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedule_times', to='med_center.MedicalCenter')),
            ],
            options={
                'verbose_name': 'Schedule Time',
                'verbose_name_plural': 'Schedule Times',
            },
        ),
    ]
