# Generated by Django 3.0.3 on 2020-05-26 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('med_center', '0003_medicalcenter_tagline'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicalcenter',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
