# Generated by Django 3.0 on 2019-12-03 12:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('med_center', '0002_auto_20191203_1213'),
    ]

    operations = [
        migrations.CreateModel(
            name='Departament',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='departament/')),
                ('med_center', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='departaments', to='med_center.MedicalCenter')),
            ],
            options={
                'verbose_name': 'Departament',
                'verbose_name_plural': 'Departaments',
            },
        ),
    ]
