# Generated by Django 3.0 on 2020-02-18 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('departament', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='departament',
            name='image',
            field=models.ImageField(help_text='only little icons', upload_to='departament/'),
        ),
    ]
