# Generated by Django 3.0.3 on 2020-03-09 06:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('med_center', '0005_auto_20191204_1240'),
        ('departament', '0002_auto_20200218_1413'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='departament',
            options={'verbose_name': 'Departament', 'verbose_name_plural': 'Departments'},
        ),
        migrations.AlterField(
            model_name='departament',
            name='med_center',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='departments', to='med_center.MedicalCenter'),
        ),
    ]
