# Generated by Django 3.0.3 on 2020-05-14 18:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('services', '0001_initial'),
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Visit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('start_time', models.DateTimeField(verbose_name='Start date')),
                ('is_finished', models.BooleanField(default=False, verbose_name='Finished')),
                ('preference', models.TextField(blank=True, null=True, verbose_name='Preference')),
                ('text', models.TextField(blank=True, null=True, verbose_name='Conclusion Text')),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visits', to='profiles.Doctor', verbose_name='Doctor')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visits', to='profiles.Patient', verbose_name='Patient')),
                ('service', models.ManyToManyField(blank=True, related_name='visits', to='services.Service', verbose_name='Service')),
            ],
            options={
                'verbose_name': 'Visit',
                'verbose_name_plural': 'Visits',
                'ordering': ['created'],
            },
        ),
        migrations.CreateModel(
            name='VisitImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='visits/2020/05/14')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('visit_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='visit.Visit')),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_approved', models.BooleanField(default=False, verbose_name='is_approved')),
                ('text', models.TextField(verbose_name='Text')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='created')),
                ('doctor_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='profiles.Doctor', verbose_name='Doctor')),
                ('patient_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='profiles.Patient', verbose_name='Patient')),
            ],
            options={
                'verbose_name': 'Review',
                'verbose_name_plural': 'Reviews',
                'ordering': ['created'],
            },
        ),
    ]
