# Generated by Django 3.0.3 on 2020-05-07 13:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('visit', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='VisitImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='visit_images/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('visit_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='visit.Visit')),
            ],
        ),
    ]
