# Generated by Django 3.0.3 on 2020-05-12 15:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
        ('services', '0001_initial'),
        ('visit', '0002_auto_20200512_1514'),
    ]

    operations = [
        migrations.AddField(
            model_name='visit',
            name='preference',
            field=models.TextField(blank=True, null=True, verbose_name='Preference'),
        ),
        migrations.AlterField(
            model_name='visit',
            name='is_finished',
            field=models.BooleanField(default=False, verbose_name='finished'),
        ),
        migrations.AlterField(
            model_name='visit',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visits', to='profiles.Patient', verbose_name='Patient'),
        ),
        migrations.AlterField(
            model_name='visit',
            name='service',
            field=models.ManyToManyField(blank=True, related_name='visits', to='services.Service', verbose_name='Doctor'),
        ),
        migrations.AlterField(
            model_name='visit',
            name='start_time',
            field=models.DateTimeField(verbose_name='Start date'),
        ),
    ]
