# Generated by Django 3.0.3 on 2020-05-13 19:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
        ('profiles', '0003_auto_20200513_1945'),
        ('visit', '0003_auto_20200512_1524'),
    ]

    operations = [
        migrations.AddField(
            model_name='visit',
            name='text',
            field=models.TextField(blank=True, null=True, verbose_name='Conclusion Text'),
        ),
        migrations.AlterField(
            model_name='visit',
            name='doctor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visits', to='profiles.Doctor', verbose_name='Doctor'),
        ),
        migrations.AlterField(
            model_name='visit',
            name='is_finished',
            field=models.BooleanField(default=False, verbose_name='Finished'),
        ),
        migrations.AlterField(
            model_name='visit',
            name='service',
            field=models.ManyToManyField(blank=True, related_name='visits', to='services.Service', verbose_name='Service'),
        ),
        migrations.AlterField(
            model_name='visitimage',
            name='image',
            field=models.ImageField(upload_to="visit_images/<attribute 'year' of 'datetime.date' objects>/<attribute 'month' of 'datetime.date' objects>/<attribute 'day' of 'datetime.date' objects>/"),
        ),
    ]
