# Generated by Django 3.0 on 2019-12-03 12:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('med_center', '0002_auto_20191203_1213'),
    ]

    operations = [
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('description', models.TextField()),
                ('address', models.CharField(max_length=500)),
                ('is_main', models.BooleanField(default=False)),
                ('med_center_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='branches', to='med_center.MedicalCenter')),
            ],
            options={
                'verbose_name': 'Branch',
                'verbose_name_plural': 'Branches',
            },
        ),
        migrations.CreateModel(
            name='BranchPhoneNumber',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=40)),
                ('branch_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='numbers', to='branch.Branch')),
            ],
            options={
                'verbose_name': 'Number',
                'verbose_name_plural': 'Numbers',
            },
        ),
    ]
